### ISSUE TITLE
Typo in README

### ISSUE THREAD

**Issue by kkalass** [greena13/react-joi-validation#1]
Hi, thanks for your excellent library!

I found a small mistake in the README: In the documentation for "Validator function interface" it states that there is a property "validateAll". It seems to be named "validateAllValues", though.

Regards,
 Klas

**Comment by greena13** [comment]
Hi Klas, thank you for your attention on this and taking the time to let me know. You are quite right. Validator functions receive a `validateAllValues` value, however the documentation incorrectly refers to `validateAll` (an older implementation).

I'll correct the mistake.

Please let me know if you encounter any more errors or potential improvements in the documentation or library itself.

P.S. If you continue to find value in this library, please consider giving it a star.
