### ISSUE TITLE
error:  `validate` undefined

### ISSUE THREAD

**Issue by amiiy** [greena13/react-joi-validation#6]
I just used this for validating my forms in reactJS.
as usage guide an imported and defined some schema and give onBlure property. but an error occurs
here:

```
import reactJoiValidation from 'react-joi-validation;
import Joi from 'joi-browser';
....
class UserForm extends React.Component {
const { validateHandler } = this.porps;
return (
...
  <input
              type="text"
              className="form-control"
              name="username"
              value={username}
              onBlur={validateHandler('username')}
              onChange={this.handleChange}
            />
...

const schema = Joi.object().keys({
  username: Joi.string().required(),
});

const validationOptions = {
  joiSchema: schema,
};

export default reactJoiValidation(UserForm, validationOptions);
```

i used this way.

When i click on input then click anotherOne(onBlur) this error thrown : 

```
index.js:566 Uncaught TypeError: Cannot read property 'validate' of undefined
    at ValidatorComponent._validate (index.js:566)
    at ValidatorComponent.validate (index.js:547)
    at index.js:539
    at Object../node_modules/react-dom/lib/ReactErrorUtils.js.ReactErrorUtils.invokeGuardedCallback (ReactErrorUtils.js:69)
    at executeDispatch (EventPluginUtils.js:85)
    at Object.executeDispatchesInOrder (EventPluginUtils.js:108)
    at executeDispatchesAndRelease (EventPluginHub.js:43)
    at executeDispatchesAndReleaseTopLevel (EventPluginHub.js:54)
    at Array.forEach (<anonymous>)
    at forEachAccumulated (forEachAccumulated.js:24)
    at Object.processEventQueue (EventPluginHub.js:254)
    at runEventQueueInBatch (ReactEventEmitterMixin.js:17)
    at Object.handleTopLevel [as _handleTopLevel] (ReactEventEmitterMixin.js:27)
    at handleTopLevelImpl (ReactEventListener.js:72)
    at ReactDefaultBatchingStrategyTransaction.perform (Transaction.js:143)
    at Object.batchedUpdates (ReactDefaultBatchingStrategy.js:62)
    at Object.batchedUpdates (ReactUpdates.js:97)
    at dispatchEvent (ReactEventListener.js:147)
_validate @ index.js:566
validate @ index.js:547
(anonymous) @ index.js:539
```

how can i fix this `validate` error ?

**Comment by greena13** [comment]
Hello, amiiy. I hope you don't mind, but I edited your post to fix the formatting of the code you included to make it easier for me to read.

Thanks for posting this issue. It looks like you may have [skipped an installation step](https://github.com/greena13/react-joi-validation#installation).

Have you included the following at an entry point in your React application (before you try to validate any components)?

```
import ReactJoiValidations from 'react-joi-validation'
import Joi from 'joi-browser' // or whatever Joi library you are using

ReactJoiValidations.setJoi(Joi); // <--- This is the bit you may be missing, or call too late.
```

Please let me know if this solves your problem, or whether we need to dig deeper.

**Comment by amiiy** [comment]
thank you! 
I don't know how I miss this! and sorry for my code format on the question. I am new to GitHub but I try to learn :)
have you any idea to scale or add some new features to this repo?
it's really interesting for me, and want to contribute! 
but i don't know how!

**Comment by amiiy** [comment]
I have changed my forms to use this library. I remove my onChangeHandler and also it helps to make this component stateless :smiley: 
but I have a select field which it's onChanges different . here is my select component: 
```
 <div className="form-group">
          <span>status</span>
          <Select
            options={UserStatus}
            labelKey="label"
            valueKey="value"
            value={status}
            onChange={option =>
              onCahnge({ status: option ? option.value : null })}
            onBlur={validateHandler('status')}
          />
        </div>
```
here how i change this onChange field to work?
iI put write this:  `changeHnadler('status')` but the 'status' field is `undefined`.
how can handle this ? :thinking:

**Comment by amiiy** [comment]
hey, i found a way!
using this customer change handler I can change any field:
```
change = ({ name, value }) => {
    const { changeValue } = this.props;
    changeValue(name, value);
    console.log(name, value);
  };
....

            onChange={val => {
              this.change({ name: 'role', value: val.key });
            }}
```

**Comment by amiiy** [comment]
sorry, dude! 
I have another question! :question: 
how can I change errors message?
can use some custom message for errors?

**Comment by greena13** [comment]
> it's really interesting for me, and want to contribute!

You could start by creating a pull request that adds a warning to the console when `validate` is called before `ReactJoiValidations.setJoi()` that provides a clearer error.

The most succinct way of dealing with your second question is to indeed use `changeValue`:

```
const { changeValue } = this.props;

<div className="form-group">
  <span>status</span>
  
  <Select
    options={UserStatus}
    labelKey="label"
    valueKey="value"
    value={status}
    onChange={ (option) => changeValue('role', { status: option ? option.value : null })}
    onBlur={validateHandler('status')}
  />
</div>
```

To answer your third question, to provide custom error messages is a little out of the scope of this package. You need to specify the error message using the joi schema that you pass to `react-joi-validation` through the [options method](https://github.com/hapijs/joi/blob/master/API.md#validatevalue-schema-options-callback):

```
import reactJoiValidation from 'react-joi-validation;
  
const schema = Joi.object().keys({
  //...
  role: Joi.any().allow('admin', 'moderator', 'user').options({
    language: {
      any: {
        allowOnly: 'Must be a recognized role'
      }
    }
  })
});

const validationOptions = {
  joiSchema: schema,
};

export default reactJoiValidation(UserForm, validationOptions);
```

You can find the full [list of default error messages here](https://github.com/hapijs/joi/blob/master/lib/language.js). Trigger the error message that you want to override, then search for it in that list and it will tell you the format of the object you need to pass to `options` as `language` in order to override it.

I'm going to close this issue for now as the original question has been resolved. If you have any more issues with the `react-joi-validation` package, please create a separate issue.
